socket prototype

diff --git a/scripts/pmctl b/scripts/pmctl
--- a/scripts/pmctl
+++ b/scripts/pmctl
@@ -39,15 +39,28 @@ init (){
 		"jack-source")
 			source=$2
 			channel_num=${3:-2}
-			channel_map="channel_map="${4:-'front-left,front-right'}
+			channel_map=""${4:-'front-left,front-right'}
 			pactl load-module module-jack-source \
 				client_name=$source \
 				source_name=$source \
 				source_properties="device.description="$source"" \
 				connect=no \
 				channels=$channel_num \
-				$channel_map 2>/dev/null || 
-					printf "Error creating virtual output $sink\n" >&2
+				channel_map=$channel_map 2>/dev/null || 
+					printf "Error creating virtual output $source\n" >&2
+
+			pactl load-module module-jack-sink \
+				client_name=$source"_sink" \
+				sink_name=$source"_sink" \
+				sink_properties="device.description="$source'_sink'"" \
+				connect=no \
+				channels=$channel_num \
+				channel_map=$channel_map 2>/dev/null || 
+					printf "Error creating virtual output $source'_sink'\n" >&2
+			for channel in $(echo $channel_map | sed 's/,/ /g'); do
+				jack_connect $source"_sink":$channel $source:$channel 2>/dev/null ||
+					printf "Error connecting jack $source to sink loopback\n" >&2
+			done
 		;;
 	esac
 }
@@ -59,24 +72,28 @@ set_primary () {
 		echo "Error setting $device $name as primary" >&2
 }
 
-create_jack_group () {
-	group=$1
-	channel_num=$2
-	channel_map=$3
+#create_jack_group () {
+	#group=$1
+	#channel_num=$2
+	#channel_map=$3
 
-	[ -z "$channel_num" -o -z "$channel_num" ] && exit
-	pactl load-module module-jack-sink \
-		client_name=$group \
-		sink_name=$group \
-		sink_properties="device.description="$group"" \
-		connect=no \
-		channels=$channel_num \
-		channel_map=$channel_map ||
-			printf "Error \n" >&2
-}
+	#[ -z "$channel_num" -o -z "$channel_num" ] && exit
+	#pactl load-module module-jack-sink \
+		#client_name=$group \
+		#sink_name=$group \
+		#sink_properties="device.description="$group"" \
+		#connect=no \
+		#channels=$channel_num \
+		#channel_map=$channel_map ||
+			#printf "Error \n" >&2
+#}
 
 jack_system_ports () {
 	jack_lsp -U 2>/dev/null | sed -n '/playback/s/.*://p'
+}
+
+jack_system_port_count () {
+	jack_lsp -U 2>/dev/null | sed -n '/playback/s/.*://p' | wc -l
 }
 
 jack_list_devices() {
@@ -141,20 +158,22 @@ jack_toggle (){
 connect_jack (){
 	source=$1
 	source_channel=$2
-	sink_channel=$3
+	sink=$3
+	sink_channel=$4
 	[ -z "$source" ] && exit
 
-	jack_connect $source:$source_channel system:playback_$sink_channel 2>/dev/null ||
+	jack_connect $source:$source_channel $sink:$sink_channel 2>/dev/null ||
 		printf "Error connecting jack $source $2 to System:$3\n" >&2
 }
 
 disconnect_jack (){
 	source=$1
 	source_channel=$2
-	sink_channel=$3
+	sink=$3
+	sink_channel=$4
 	[ -z "$source" ] && exit
 
-	jack_disconnect $source:$source_channel system:playback_$sink_channel 2>/dev/null ||
+	jack_disconnect $source:$source_channel $sink:$sink_channel 2>/dev/null ||
 		printf "Error disconnecting jack $source $2 to System:$3\n" >&2
 }
 
@@ -254,7 +273,7 @@ list (){
 	list=$(LC_ALL=C pactl list $1 | \
 		awk '/Sink #/{print $2} /Source #/{print $2} /Name:/ {print $0} 
 			/Description/ {print $0} /ladspa/{print $0} /remap-source/ {print $0}
-			/module-null-sink/ {print $0} /module-jack-sink/ {print $0} /Volume/ {print $0} /null-audio-sink/ {print $0}' |\
+			/module-null-sink/ {print $0} /module-jack-sink/ {print $0} /module-jack-source/ {print $0} /Volume/ {print $0} /null-audio-sink/ {print $0}' |\
 			sed '/Base Volume/d; s/%.*//g; s/:.*\/ /: /g; /Volume/s/$/%/; s/: /:"/g; /#/!s/$/"/g;')
 
 	#echo "$list"
@@ -617,10 +636,10 @@ case $1 in
 		get_source_output_volume $2
 	;;
 	"jack-connect")
-		connect_jack $2 $3 $4
+		connect_jack $2 $3 $4 $5
 	;;
 	"jack-disconnect")
-		disconnect_jack $2 $3 $4
+		disconnect_jack $2 $3 $4 $5
 	;;
 	"jack-list")
 		jack_list $2
@@ -636,6 +655,9 @@ case $1 in
 	;;
 	"jack-system-ports")
 		jack_system_ports
+	;;
+	"jack-system-port-count")
+		jack_system_port_count
 	;;
 	"jack-create-group")
 		create_jack_group $2 $3 $4
